name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        run: |
          docker build -t parfenovakg/infra-backend:latest ./backend
          docker push parfenovakg/infra-backend:latest

      - name: Build and push frontend
        run: |
          docker build -t parfenovakg/infra-frontend:latest ./frontend
          docker push parfenovakg/infra-frontend:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/foodgram
            docker pull parfenovakg/infra-backend:latest
            docker pull parfenovakg/infra-frontend:latest
            docker compose -f docker-compose.production.yml up -d
